from api import login
from api import profile
from api import leave
from api import homework
from api import calendar
from api import submitleave
from api import schedule_student
from api import score
from api import grade